1. Define a Large Language Model in your own words and explain what it means for a model to "learn the patterns of language."

Answer:

A Large Language Model (LLM) is an AI model trained on a large amount of text to understand and generate human language. It can answer questions, write content, and perform many language tasks. Learning the patterns of language means it understands how words and sentences are used together instead of simply memorizing them.

2. Explain why LLMs are called "large." Discuss both the training data dimension and the parameter dimension.

Answer:

LLMs are called "large" because they are trained on huge amounts of text data and have billions of parameters. The large dataset helps the model learn different language patterns, while the large number of parameters allows it to store and use that knowledge effectively to generate accurate responses.

3. Describe the evolution of language models from rule-based systems to modern LLMs, explaining why each stage improved on the previous one.

Answer:

Language models started with rule-based systems that followed fixed grammar rules. They later evolved into statistical models, then RNNs and LSTMs, which could learn from data but struggled with long sentences. Transformers solved these problems using self-attention, leading to modern LLMs that are faster and more accurate.

4. Explain the key limitations of RNNs and LSTMs that motivated the invention of the Transformer architecture.

Answer:

RNNs and LSTMs process words one at a time, making them slow to train. They also struggle to remember information from long sentences. Transformers overcome these limitations by processing all words together using self-attention, making them faster and better at understanding context.

5. What is self-attention, and how does it allow a Transformer to overcome the long-range dependency problem faced by older models?

Answer:

Self-attention allows each word in a sentence to focus on other important words to understand the overall meaning. This helps the model capture relationships between words that are far apart in a sentence. As a result, Transformers understand context better than older models like RNNs and LSTMs.

6. List and explain three real-world limitations of LLMs (e.g. hallucination, knowledge cutoff, context window), and suggest one way to mitigate each.

Answer:

Hallucination: LLMs may generate incorrect or made-up information. This can be reduced by verifying responses with reliable sources.
Knowledge Cutoff: LLMs may not know recent events because they are trained on past data. Using web search or updated models helps solve this.
Context Window: LLMs can only process a limited amount of text at once. Breaking large documents into smaller sections or using retrieval techniques can help.

7. Differentiate between open-weight and closed/hosted LLMs, giving at least two examples of each and comparing their trade-offs.

Answer:

Open-weight LLMs allow users to download and run the model locally. Examples include Llama and Mistral. Closed or hosted LLMs are accessed through APIs and their model weights are not publicly available. Examples include GPT-4 and Claude. Open models offer more control and customization, while closed models are easier to use and are usually more powerful.

8. Explain why an LLM cannot process raw text directly and describe the role tokenization plays in bridging this gap.

Answer:

An LLM cannot understand raw text because computers work with numbers, not words. Tokenization converts text into smaller units called tokens and assigns each token a unique ID. These token IDs are then used as input for the model.

9. Compare character-level, word-level, and subword-level tokenization, listing one advantage and one disadvantage of each.

Answer:

Character-level: Splits text into individual characters. It can handle any word but creates very long sequences.
Word-level: Splits text into complete words. It is simple but cannot handle unknown words well.
Subword-level: Splits words into smaller meaningful parts. It handles rare words efficiently but is slightly more complex than the other methods.

10. Describe how Byte Pair Encoding (BPE) builds its vocabulary, using a short example of the merge process.

Answer:

Byte Pair Encoding (BPE) starts with individual characters and repeatedly merges the most frequently occurring pair of characters or subwords. For example, the word "lowest" may first be split into l, o, w, e, s, t. Frequent pairs like lo, low, and est are merged over time to form larger subword tokens. This helps reduce vocabulary size while handling rare words efficiently.

11. Explain the difference between WordPiece and SentencePiece tokenization, including a scenario where each would be preferred.

Answer:

WordPiece builds tokens based on the most likely subwords using training data, while SentencePiece treats text as a sequence of characters without requiring spaces. WordPiece is commonly used in BERT, whereas SentencePiece is preferred for multilingual models like T5 because it works well with different languages.

12. What are special tokens (e.g. <PAD>, <CLS>, <SEP>, <MASK>) used for, and why does a model need them?

Answer:

Special tokens provide extra information to the model. <PAD> is used to make all sequences the same length, <CLS> represents the entire input, <SEP> separates different sentences, and <MASK> is used during masked language model training. These tokens help the model process and understand text correctly.

13. Explain the purpose of an attention mask in the context of padded sequences.

Answer:

An attention mask tells the model which tokens are actual words and which are padding tokens. It ensures that the model ignores the padded positions while calculating attention, leading to more accurate results.

14. Explain why token IDs alone are not sufficient input for a Transformer, and how embeddings solve this problem.

Answer:

Token IDs are just numbers and do not contain any meaning. The embedding layer converts these IDs into dense vectors that capture semantic information. These embeddings allow the Transformer to understand relationships between different words.

15. Compare one-hot encoding with dense embeddings in terms of memory efficiency and semantic meaning.

Answer:

One-hot encoding creates large sparse vectors where each word is represented independently, making it memory-intensive and unable to capture meaning. Dense embeddings use smaller vectors that are memory-efficient and represent semantic relationships between words.

16. Describe how the embedding layer works as a lookup table, and explain whether embeddings are meaningful before training begins.

Answer:

The embedding layer acts like a lookup table where each token ID is mapped to a vector. Initially, these vectors are random and have no meaning. During training, the model updates them so that similar words have similar embeddings.

17. What is the difference between input embeddings and output embeddings in a Transformer, and what is "weight tying"?

Answer:

Input embeddings convert token IDs into vectors before processing. Output embeddings are used to convert the model's output back into token probabilities. Weight tying means using the same weights for both input and output embeddings, reducing memory usage and improving efficiency.

18. Explain what positional embeddings are for, using the "Dog bites man" vs. "Man bites dog" example to justify your answer.

Answer:

Transformers process all words together, so they need positional embeddings to know the order of words. For example, "Dog bites man" and "Man bites dog" contain the same words but have different meanings because of their order. Positional embeddings help the model distinguish between such sentences.

19. Explain contextual embeddings using the word "bank" as an example, and contrast this with traditional fixed embeddings.

Answer:

Contextual embeddings change based on the meaning of a word in a sentence. For example, "bank" refers to a financial institution in one sentence and the side of a river in another, so it gets different embeddings. Traditional fixed embeddings always assign the same vector to a word, regardless of context.

20. Explain cosine similarity as a measure of semantic closeness between two embedding vectors, including what values of -1, 0, and 1 represent.

Answer:

Cosine similarity measures how similar two embedding vectors are by comparing the angle between them. A value of 1 means the vectors are very similar, 0 means they are unrelated, and -1 means they are completely opposite. It is commonly used to compare the semantic similarity of words or sentences.

21. Using Hugging Face's transformers library, load the gpt2 tokenizer and tokenize the sentence:

"Large Language Models are transforming the world."

Print the resulting tokens and their token IDs.

In [1]:
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

sentence = "Large Language Models are transforming the world."

tokens = tokenizer.tokenize(sentence)

token_ids = tokenizer.encode(sentence)

print("Tokens:")
print(tokens)

print("\nToken IDs:")
print(token_ids)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Tokens:
['Large', 'ĠLanguage', 'ĠModels', 'Ġare', 'Ġtransforming', 'Ġthe', 'Ġworld', '.']

Token IDs:
[21968, 15417, 32329, 389, 25449, 262, 995, 13]


22. Using AutoTokenizer, compare how the words "unbelievable" and "cat" are tokenized. Explain why one is split into multiple tokens and the other is not.

In [2]:
from transformers import AutoTokenizer


tokenizer = AutoTokenizer.from_pretrained("gpt2")

words = ["unbelievable", "cat"]

for word in words:
    tokens = tokenizer.tokenize(word)
    token_ids = tokenizer.encode(word)

    print(f"\nWord: {word}")
    print("Tokens:", tokens)
    print("Token IDs:", token_ids)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]


Word: unbelievable
Tokens: ['un', 'bel', 'iev', 'able']
Token IDs: [403, 6667, 11203, 540]

Word: cat
Tokens: ['cat']
Token IDs: [9246]


23. Using the pipeline API, load GPT-2 and generate text from the prompt:

Artificial Intelligence is

Run it twice and compare the outputs.

In [3]:
import transformers
print(transformers.__version__)

5.13.1


In [4]:
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [5]:
import torch

print(torch.__version__)

2.11.0+cpu


In [6]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "distilgpt2"   # Smaller GPT-2 model

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

prompt = "Artificial Intelligence is"

inputs = tokenizer(prompt, return_tensors="pt")

for i in range(2):
    output = model.generate(
        **inputs,
        max_new_tokens=50,
        do_sample=True,
        temperature=0.8
    )

    print(f"\nOutput {i+1}:\n")
    print(tokenizer.decode(output[0], skip_special_tokens=True))

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  353MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]


Output 1:

Artificial Intelligence is the world's most advanced artificial intelligence (AI) designed to learn what you can do, which is useful for teaching them how to work as humans. They are also able to design systems that have the capacity of working in the real world.



Output 2:

Artificial Intelligence is a process of processing, processing, or processing objects. It’s the result of the process of processing and processing objects. As the processing of non-intrusive objects occurs, they are not just objects that are not displayed in the display


24. Pad a batch of three sentences of different lengths and print the attention mask.

In [7]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

sentences = [
    "I love AI.",
    "Transformers are powerful models.",
    "Natural Language Processing is interesting."
]

encoded = tokenizer(
    sentences,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

print("Input IDs:")
print(encoded["input_ids"])

print("\nAttention Mask:")
print(encoded["attention_mask"])

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Input IDs:
tensor([[  101,  1045,  2293,  9932,  1012,   102,     0,     0],
        [  101, 19081,  2024,  3928,  4275,  1012,   102,     0],
        [  101,  3019,  2653,  6364,  2003,  5875,  1012,   102]])

Attention Mask:
tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])


25. Using bert-base-uncased, extract the embedding vector for the word "bank" in two different sentences and compare them numerically.

In [8]:
from transformers import AutoTokenizer, AutoModel
import torch

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

sentences = [
    "I deposited money in the bank.",
    "The fisherman sat on the bank of the river."
]

embeddings = []

for sentence in sentences:
    inputs = tokenizer(sentence, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)

    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

    # Find the position of "bank"
    bank_index = tokens.index("bank")

    bank_embedding = outputs.last_hidden_state[0, bank_index]
    embeddings.append(bank_embedding)

# Euclidean distance
distance = torch.norm(embeddings[0] - embeddings[1])

print("Embedding Shape:", embeddings[0].shape)
print("Distance between embeddings:", distance.item())

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Embedding Shape: torch.Size([768])
Distance between embeddings: 16.09947395324707


26. Using sentence-transformers (all-MiniLM-L6-v2), encode the sentences and compute the cosine similarity matrix.

In [9]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Load model
model = SentenceTransformer("all-MiniLM-L6-v2")

sentences = [
    "Artificial Intelligence",
    "Machine Learning",
    "I love pizza"
]

# Generate embeddings
embeddings = model.encode(sentences)

# Cosine similarity matrix
similarity = cosine_similarity(embeddings)

print("Cosine Similarity Matrix:")
print(similarity)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Cosine Similarity Matrix:
[[1.0000001  0.7034625  0.1269484 ]
 [0.7034625  1.0000001  0.08875057]
 [0.1269484  0.08875057 1.0000001 ]]


27. Implement scaled dot-product self-attention from scratch in PyTorch

In [10]:
import torch
import torch.nn.functional as F
import math

torch.manual_seed(42)

# Example Q, K, V matrices
Q = torch.rand(3, 4)
K = torch.rand(3, 4)
V = torch.rand(3, 4)

# Scaled Dot Product Attention
scores = torch.matmul(Q, K.T)

scaled_scores = scores / math.sqrt(Q.size(-1))

attention_weights = F.softmax(scaled_scores, dim=-1)

context = torch.matmul(attention_weights, V)

print("Attention Scores:")
print(scores)

print("\nAttention Weights:")
print(attention_weights)

print("\nContext Vectors:")
print(context)

Attention Scores:
tensor([[1.9822, 2.0103, 1.5533],
        [1.2115, 1.2569, 1.1067],
        [1.8410, 1.5310, 1.0836]])

Attention Weights:
tensor([[0.3545, 0.3595, 0.2860],
        [0.3365, 0.3442, 0.3193],
        [0.3935, 0.3370, 0.2695]])

Context Vectors:
tensor([[0.4875, 0.2646, 0.5658, 0.3291],
        [0.5067, 0.2790, 0.5561, 0.3513],
        [0.4646, 0.2653, 0.5529, 0.3218]])


28. Extend self-attention to multi-head attention with 4 heads for embedding dimension 32.

In [11]:
import torch
import torch.nn as nn

embed_dim = 32
num_heads = 4

mha = nn.MultiheadAttention(
    embed_dim=embed_dim,
    num_heads=num_heads,
    batch_first=True
)

# Random input
x = torch.rand(2, 5, embed_dim)

output, weights = mha(x, x, x)

print("Input Shape :", x.shape)
print("Output Shape:", output.shape)
print("Attention Shape:", weights.shape)

Input Shape : torch.Size([2, 5, 32])
Output Shape: torch.Size([2, 5, 32])
Attention Shape: torch.Size([2, 5, 5])


29. Implement a causal (look-ahead) mask for a 5-token sequence.

In [12]:
import torch
import torch.nn.functional as F

torch.manual_seed(42)

scores = torch.rand(5, 5)

print("Original Scores:")
print(scores)

# Causal mask
mask = torch.triu(torch.ones(5, 5), diagonal=1).bool()

masked_scores = scores.masked_fill(mask, float('-inf'))

attention = F.softmax(masked_scores, dim=-1)

print("\nMasked Scores:")
print(masked_scores)

print("\nAttention after Softmax:")
print(attention)

Original Scores:
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]])

Masked Scores:
tensor([[0.8823,   -inf,   -inf,   -inf,   -inf],
        [0.6009, 0.2566,   -inf,   -inf,   -inf],
        [0.9346, 0.5936, 0.8694,   -inf,   -inf],
        [0.4294, 0.8854, 0.5739, 0.2666,   -inf],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]])

Attention after Softmax:
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5852, 0.4148, 0.0000, 0.0000, 0.0000],
        [0.3777, 0.2685, 0.3538, 0.0000, 0.0000],
        [0.2182, 0.3443, 0.2521, 0.1854, 0.0000],
        [0.1719, 0.2041, 0.1766, 0.3015, 0.1458]])


30. Build a minimal GPT-style decoder block.

In [13]:
import torch
import torch.nn as nn

class GPTDecoderBlock(nn.Module):
    def __init__(self, embed_dim=32, num_heads=4):
        super().__init__()

        self.attention = nn.MultiheadAttention(
            embed_dim,
            num_heads,
            batch_first=True
        )

        self.norm1 = nn.LayerNorm(embed_dim)

        self.ffn = nn.Sequential(
            nn.Linear(embed_dim, 64),
            nn.ReLU(),
            nn.Linear(64, embed_dim)
        )

        self.norm2 = nn.LayerNorm(embed_dim)

    def forward(self, x):

        attn_output, _ = self.attention(x, x, x)

        x = self.norm1(x + attn_output)

        ffn_output = self.ffn(x)

        x = self.norm2(x + ffn_output)

        return x


model = GPTDecoderBlock()

x = torch.rand(2, 5, 32)

output = model(x)

print("Input Shape :", x.shape)
print("Output Shape:", output.shape)

Input Shape : torch.Size([2, 5, 32])
Output Shape: torch.Size([2, 5, 32])
